In [6]:
import pandas as pd

df = pd.DataFrame()
display(df)
print(df.shape)

Empty DataFrame
Columns: []
Index: []

(0, 0)

In [7]:
data = [10, 20, 30, 40, 50]
df = pd.DataFrame(data)
display(df)

    0
0  10
1  20
2  30
3  40
4  50

In [8]:
data = [
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150]
]

df = pd.DataFrame(
    data,
    columns=["c1", "c2", "c3", "c4", "c5"],
    index=["r1", "r2", "r3"]
)
display(df)
print(df.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [9]:
print(df.columns)
print(df.index)

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')
Index(['r1', 'r2', 'r3'], dtype='object')

In [10]:
df.to_csv("data.csv", index=True)
print("CSV File Created Successfully!")

CSV File Created Successfully!

In [15]:
df2 = pd.read_csv("data.csv", index_col=0)
display(df2)
print(df2.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [13]:
df3=pd.read_csv("data.csv", index_col=0)
display(df3)
print(df3.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [17]:
df3.to_csv("data.csv", index=True)
print("CSV File Created Successfully!")
df3.to_excel("data.xlsx", index=True)
print("Excel File Created Successfully!")

CSV File Created Successfully!
Excel File Created Successfully!

In [18]:
#csv Import
csv_df= pd.read_csv("data.csv", index_col=0)
display(csv_df)
print(csv_df.shape)
#excel Import
excel_df=pd.read_excel("data.xlsx", index_col=0)
display(excel_df)
print(excel_df.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [ ]:
#import csv file
df = pd.read_csv("demo.csv", index_col=0)
display(df)
print(df.shape)

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95
r6   120   95   70   45   20
r7    12   24   36   48   60
r8    75   50   25  100  125
r9    33   66   99  132  165
r10    5   15   25   35   45

(10, 5)

In [20]:
#import excel file
df.to_excel("demo.xlsx", index=True)
print("Excel File Created Successfully!")

Excel File Created Successfully!

In [21]:
df_excel = pd.read_excel("demo.xlsx", index_col=0)
display(df_excel)
print(df_excel.shape)

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95
r6   120   95   70   45   20
r7    12   24   36   48   60
r8    75   50   25  100  125
r9    33   66   99  132  165
r10    5   15   25   35   45

(10, 5)

In [22]:
print(df.equals(df_excel))

True