In [2]:
import pandas as pd

df = pd.read_csv("nasdaq100.csv", sep=";")

In [3]:
df.head()

       Date  Starting (USD)  Ending (USD)
0  01.01.24           16800         16500
1  01.12.23           15900         16100
2  01.11.23           15800         15300
3  01.10.23           16100         16200
4  01.09.23           16300         15700

In [4]:
df.tail()

        Date  Starting (USD)  Ending (USD)
7   01.06.23           15800         15500
8   01.05.23           16150         16100
9   01.04.23           16300         15800
10  01.03.23           16200         16200
11  01.02.23           16300         15700

In [5]:
display(df.shape)

(12, 3)

In [8]:
display(df.columns)

Index(['Date', 'Starting (USD)', 'Ending (USD)'], dtype='object')

In [11]:
display(df)

        Date  Starting (USD)  Ending (USD)
0   01.01.24           16800         16500
1   01.12.23           15900         16100
2   01.11.23           15800         15300
3   01.10.23           16100         16200
4   01.09.23           16300         15700
5   01.08.23           16800         16400
6   01.07.23           15900         16200
7   01.06.23           15800         15500
8   01.05.23           16150         16100
9   01.04.23           16300         15800
10  01.03.23           16200         16200
11  01.02.23           16300         15700

In [12]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Date              0
Starting (USD)    0
Ending (USD)      0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            12 non-null     object
 1   Starting (USD)  12 non-null     int64
 2   Ending (USD)    12 non-null     int64
dtypes: int64(2), object(1)
memory usage: 416.0+ bytes