In [2]:
import pandas as pd

df = pd.read_csv("car_risk.csv")

df.head()

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82

In [3]:
print(df.isnull().sum())

speed         0
car_age       0
experience    1
risk          0
dtype: int64

In [4]:
median_value = df["experience"].median()
df["experience"] = df["experience"].fillna(median_value)
print("Median:", median_value)

display(df)

Median: 5.0

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10

In [5]:

from sklearn.linear_model import LinearRegression

# Independent Variables (Features)
X = df[["speed", "car_age", "experience"]]

# Dependent Variable (Target)
y = df["risk"]

# Create Model
model = LinearRegression()

# Train Model Relationship
model.fit(X, y)

print("Model Training Completed!")

Model Training Completed!

In [6]:
print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (6, 3)
y Shape: (6,)

In [7]:
# Get coefficients
print("Coefficients:", model.coef_)

# Get intercept
print("Intercept:", model.intercept_)

Coefficients: [ 0.33059217  1.61053246 -6.20772074]
Intercept: 33.41000091043588

In [8]:
print("Speed Coefficient:", model.coef_[0])
print("Car Age Coefficient:", model.coef_[1])
print("Experience Coefficient:", model.coef_[2])

Speed Coefficient: 0.3305921679478319
Car Age Coefficient: 1.6105324616036159
Experience Coefficient: -6.207720735623532

In [9]:
# New Input Data
new_data = pd.DataFrame({
    "speed": [160],
    "car_age": [10],
    "experience": [5]
})

# Predict Risk
prediction = model.predict(new_data)

print("Predicted Risk:", prediction[0])

Predicted Risk: 71.3714687200075

In [10]:
new_data2 = pd.DataFrame({
    "speed": [120],
    "car_age": [8],
    "experience": [10]
})

prediction2 = model.predict(new_data2)

print("Predicted Risk:", prediction2[0])

Predicted Risk: 23.88811340076932

In [11]:
# Predict training dataset
y_pred = model.predict(X)

# Compare actual and predicted values
comparison = pd.DataFrame({
    "Actual Risk": y,
    "Predicted Risk": y_pred
})

print(comparison.round(2))

   Actual Risk  Predicted Risk
0           85           92.65
1           20            9.84
2           93           82.45
3           60           70.95
4           82           69.12
5           10           24.99

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print("MAE:", round(mae, 2))
print("MSE:", round(mse, 2))
print("R2 Score:", round(r2, 4))

MAE: 11.19
MSE: 130.53
R2 Score: 0.8753