In [2]:
import pandas as pd

df = pd.DataFrame()
display(df)
print(df.shape)

Empty DataFrame
Columns: []
Index: []

(0, 0)

In [3]:
data = [10, 20, 30, 40, 50]
df = pd.DataFrame(data)
display(df)

    0
0  10
1  20
2  30
3  40
4  50

In [4]:
data = [
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150]
]

df = pd.DataFrame(
    data,
    columns=["c1", "c2", "c3", "c4", "c5"],
    index=["r1", "r2", "r3"]
)
display(df)
print(df.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [5]:
print(df.columns)
print(df.index)

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')
Index(['r1', 'r2', 'r3'], dtype='object')

In [6]:
df.to_csv("data.csv", index=True)
print("CSV File Created Successfully!")

CSV File Created Successfully!

In [7]:
df2 = pd.read_csv("data.csv", index_col=0)
display(df2)
print(df2.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [8]:
df3=pd.read_csv("data.csv", index_col=0)
display(df3)
print(df3.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [9]:
#csv Import
df3.to_csv("data.csv", index=True)
print("CSV File Created Successfully!")

#excel Import
df3.to_excel("data.xlsx", index=True)
print("Excel File Created Successfully!")

CSV File Created Successfully!
Excel File Created Successfully!

In [10]:
csv_df= pd.read_csv("data.csv", index_col=0)
display(csv_df)
print(csv_df.shape)

excel_df=pd.read_excel("data.xlsx", index_col=0)
display(excel_df)
print(excel_df.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [11]:
#import csv file
df = pd.read_csv("demo.csv", index_col=0)
display(df)
print(df.shape)

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95
r6   120   95   70   45   20
r7    12   24   36   48   60
r8    75   50   25  100  125
r9    33   66   99  132  165
r10    5   15   25   35   45

(10, 5)

In [12]:
#import excel file
df.to_excel("demo.xlsx", index=True)
print("Excel File Created Successfully!")

Excel File Created Successfully!

In [13]:
df_excel = pd.read_excel("demo.xlsx", index_col=0)
display(df_excel)
print(df_excel.shape)

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95
r6   120   95   70   45   20
r7    12   24   36   48   60
r8    75   50   25  100  125
r9    33   66   99  132  165
r10    5   15   25   35   45

(10, 5)

In [14]:
print(df.equals(df_excel))

True

In [16]:
print(df.values)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [ 25  45  65  85 105]
 [ 15  35  55  75  95]
 [120  95  70  45  20]
 [ 12  24  36  48  60]
 [ 75  50  25 100 125]
 [ 33  66  99 132 165]
 [  5  15  25  35  45]]

In [17]:
display(df[['c1', 'c2', 'c3']])

      c1   c2   c3
Row
r1    10   20   30
r2    60   70   80
r3   110  120  130
r4    25   45   65
r5    15   35   55
r6   120   95   70
r7    12   24   36
r8    75   50   25
r9    33   66   99
r10    5   15   25

In [18]:
print(df.index)
display(df)

Index(['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'], dtype='object', name='Row')

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95
r6   120   95   70   45   20
r7    12   24   36   48   60
r8    75   50   25  100  125
r9    33   66   99  132  165
r10    5   15   25   35   45

In [19]:
df_asc=df.sort_values(by='c1', ascending=True)
display(df_asc)

      c1   c2   c3   c4   c5
Row
r10    5   15   25   35   45
r1    10   20   30   40   50
r7    12   24   36   48   60
r5    15   35   55   75   95
r4    25   45   65   85  105
r9    33   66   99  132  165
r2    60   70   80   90  100
r8    75   50   25  100  125
r3   110  120  130  140  150
r6   120   95   70   45   20

In [20]:
display(df.describe())

               c1         c2         c3         c4        c5
count   10.000000   10.00000   10.00000   10.00000   10.0000
mean    46.500000   54.00000   61.50000   79.00000   91.5000
std     42.570856   34.11093   34.76029   37.59137   47.3785
min      5.000000   15.00000   25.00000   35.00000   20.0000
25%     12.750000   26.75000   31.50000   45.75000   52.5000
50%     29.000000   47.50000   60.00000   80.00000   97.5000
75%     71.250000   69.00000   77.50000   97.50000  120.0000
max    120.000000  120.00000  130.00000  140.00000  165.0000

In [21]:
display(df)

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95
r6   120   95   70   45   20
r7    12   24   36   48   60
r8    75   50   25  100  125
r9    33   66   99  132  165
r10    5   15   25   35   45

In [22]:
df.head()

      c1   c2   c3   c4   c5
Row
r1    10   20   30   40   50
r2    60   70   80   90  100
r3   110  120  130  140  150
r4    25   45   65   85  105
r5    15   35   55   75   95

In [23]:
df.tail()

      c1  c2  c3   c4   c5
Row
r6   120  95  70   45   20
r7    12  24  36   48   60
r8    75  50  25  100  125
r9    33  66  99  132  165
r10    5  15  25   35   45